### ISSUE TITLE
red error screen

### ISSUE THREAD

**Issue by BURGERxBOY** [BURGERxBOY/alternate-player-for-twitch.tv-public-bug-issue-list#12]
![alternate player for twitch rare red error](https://github.com/BURGERxBOY/alternate-player-for-twitch.tv-public-bug-issue-list/assets/135216471/3ce26d25-2283-4bc7-b40c-416f341bc37f)
here's the debug stuff it has with it:

{"ПричинаЗавершенияРаботы":"Error: Неизвестный адрес: https://usw23.playlist.live-video.net/v1/playlist/CsgFY-UNv-kZsE5DctZOfabkimOsxcBk9fhYGde8MudWwRS8JAGbYJi07SRotDUorLVzczPgv3eZx4dyngWHt1jw-rLcn6zxj3n3w2JGNKsBVGcGooDHyrKMixN6lzHu_y-9wtrsIdDZMASwDlGpoMi7gaBQ4lUP9EuigSWijwvd7uGydEjTTDI_Ysz2-EYziJNDFkkNSHBUtnM6mehGNtaf6v0X4E9cNDWMZCM70xeHwPYQM2i4UC633p3ruyxj_5FeH3-eQihTXft38N5Vz_Zsl6ksQ-Tc7Psa5lu8qHmzvRYIBljnSoPCDgchlDcBarLfuaQrTrpGKeAHWVShSzhKMhQCZO-melQ5k7-na78WqAlS0Ci9w1NWxFdj_uUNDBRkSOKHnySR5ymKbd2o2XTdLaQpKfTLHXAzl868RjDUHmE0ipSAYuKuiwF9FnrOTS0Hk7vsFT3y6JRIPd7ORsdtJxUyj6J1xnEtsLnmO_k4j57FiDLCByXvUjRSVJVbNEVeHRWuANQXuwcCt3eY6CXy7NLwGY9sifZVWsaZ2-yIm1ktEZT1IH4kekJy7niAG4zTYbDi_T7OmWxOScpsMaZLLlhFUiye5P98rSADHl39IHrZ3SMUVjxTA6VGNfMKUOJiN0cKSr65e69xfrXLc9qWAje_K1kqxAK0REhg8cXZUx2Vsb_1l9FMo_R2YJyP7ynKX8SWgmfYySn7IeIGnYjpxi4A9S3IEU34NihnZbc31lwX9AzpbVs2zQQI1VnNx4RBSc7VHPflAEoRRwPT6H8eWYZ7x8syfalCAebRno0bV1o2TAOJmfQ0wm0UFQC4dz9wFOCvg6Bq1RFI3BoWqchNh4V3d_WHFPb3i3Kw32Zm153aFu0taXcg4lElW1aUcrmnalzb1p9wtmO2tHs_M1Itzml2CFhOShW6cyuF680ze6JkHwXEbrU_AhoM85F1LKG1Ru8YiM6-IAEqCXVzLXdlc3QtMjCPCQ.m3u8\n    at Object.проверитьДоступностьАдреса (chrome-extension://bhplkbgoehhhddaoolmakpocnenplmhf/player.js:5457:10)\n    at Загрузить (chrome-extension://bhplkbgoehhhddaoolmakpocnenplmhf/player.js:5176:12)\n    at Object.ЗагрузитьТекст (chrome-extension://bhplkbgoehhhddaoolmakpocnenplmhf/player.js:5163:10)\n    at chrome-extension://bhplkbgoehhhddaoolmakpocnenplmhf/player.js:4411:24","ВерсияРасширения":"2022.2.7.1","Оборзеватель":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36","Время":"2024-04-05T21:23:06.739Z","Рассинхронизация":-5008004,"Адрес":"chrome-extension://bhplkbgoehhhddaoolmakpocnenplmhf/player.html?channel=solegenddairy","Инкогнито":false,"Языки":"en-US | en-US,en | Untitled","Фокусник":{"лПоказан":true,"лАктивен":false},"Пульс":0,"Настройки":{"чВерсияНастроек":2,"чСлучайноеЧисло":0.5341095705912817,"сПредыдущаяВерсия":"2022.2.7.1","чПоследняяПроверкаОбновленияРасширения":1712155028039,"чГромкость2":100,"сНазваниеВарианта":"chunked","чДлительностьПовтора2":-9007199254740991,"чСостояниеЧата":2,"лАвтоПоложениеЧата":true,"лМенятьГромкостьКолесом":false,"лПоказатьСтатистику":true,"сПредустановкаВыбрана_буферизация":"J0129","лПредустановкаЗаполнена_буферизация":true,"кОдновременныхЗагрузок":3,"чНачалоВоспроизведения":1.5,"чРазмерБуфера":1.5,"чРастягиваниеБуфера":9,"сПредустановкаВыбрана_оформление":"J0123","лПредустановкаЗаполнена_оформление":true,"сЦветФона":"#ff8000","сЦветГрадиента":"#ffff00","сЦветКнопок":"#402000","сЦветЗаголовка":"#ffff00","сЦветВыделения":"#ff8000","лАвтоперенаправлениеЗамечено":true},"Статистика":{"ПараметрыВидео":" ","ПараметрыЗвука":"","ЗабракованныхСегментов":0,"ПропущенныхСегментов":0,"ОшибокЗагрузки":0,"НезагруженныхСегментов":0,"ПотерьВидео":0,"ПотерьЗвука":0,"ИсчерпанийБуфера":0,"ИсчерпанийБуфераДосрочно":0,"ПереполненийБуфера":0,"ПропущеноВБуфере":0,"Реклама":"0 "},"УстановкиДаты":{"locale":"en-US","calendar":"gregory","numberingSystem":"latn","timeZone":"Australia/Adelaide","year":"numeric","month":"numeric","day":"numeric","timezoneOffset":-630},"Видюха":"Google Inc. (NVIDIA) | ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Laptop GPU (0x00002520) Direct3D11 vs_5_0 ps_5_0, D3D11)","ПроцессорИОперативка":{"modelName":"11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz","archName":"x86_64","numOfProcessors":16,"capacity":15.8,"availableCapacity":2.4},"Экран":{"width":1366,"height":768,"availTop":0,"availLeft":0,"availWidth":1366,"availHeight":720,"colorDepth":24,"pixelDepth":24,"orientation":"landscape-primary","screenX":0,"screenY":0,"outerWidth":1366,"outerHeight":720,"innerWidth":1366,"innerHeight":633,"devicePixelRatio":1},"ТокенТрансляции":"ИдУстройства=d1k8jBjR1zgXgQpBq1cM7J7NjEWGbS5L ТокенЗрителя=true\n{\"adblock\":false,\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"blackout_enabled\":false,\"channel\":\"solegenddairy\",\"channel_id\":491956882,\"chansub\":{\"restricted_bitrates\":[],\"view_until\":1924905600},\"ci_gb\":false,\"geoblock_reason\":\"\",\"device_id\":\"d1k8jBjR1zgXgQpBq1cM7J7NjEWGbS5L\",\"expires\":1712358394,\"extended_history_allowed\":false,\"game\":\"\",\"hide_ads\":false,\"https_required\":true,\"mature\":false,\"partner\":false,\"platform\":\"web\",\"player_type\":\"site\",\"private\":{\"allowed_to_view\":true},\"privileged\":false,\"role\":\"\",\"server_ads\":true,\"show_ads\":true,\"subscriber\":false,\"turbo\":false,\"user_id\":611531873,\"user_ip\":\"122.108.193.112\",\"version\":2}","ТокенТрансляцииБезРекламы":"","СписокВариантов":"#EXTM3U\n#EXT-X-TWITCH-INFO:NODE=\"cloudfront_prod_usw23\",MANIFEST-NODE-TYPE=\"weaver_cluster\",MANIFEST-NODE=\"elastic-weaver.usw23\",SUPPRESS=\"true\",SERVER-TIME=\"1712357194.69\",TRANSCODESTACK=\"2017TranscodeX264_V2\",TRANSCODEMODE=\"cbr_v1\",USER-IP=\"122.108.193.112\",SERVING-ID=\"27a13780c16840c3ac25421c9b195656\",CLUSTER=\"cloudfront_prod_usw23\",ABS=\"true\",VIDEO-SESSION-ID=\"7157646474956033036\",BROADCAST-ID=\"42551990718\",STREAM-TIME=\"2769.687342\",FUTURE=\"true\",B=\"false\",USER-COUNTRY=\"AU\",MANIFEST-CLUSTER=\"usw23\",ORIGIN=\"usw23\",C=\"aHR0cHM6Ly92aWRlby1lZGdlLWYxMzM4Ny5wZHgwMS5hYnMuaGxzLnR0dm53Lm5ldC92MS9zZWdtZW50L0NwYmo5NDlsN3FQQXZxTm1JQlNYTWk4MjVDRk9JallUeUtpTUVQLUNic3RlTzgtZE5qM2pUUUJQNnBwd2phNjZfWHk0ZXVodzA0YVJkOVhlZ0xBRTBOanJmTEdBcXZOWU1NSVBzVVVhTFNsaHFiN1RhTXVnZ1RyTW5MNHpnVmI4akdHTngtT0w2LVhKTXNsZDhTNlBfQWdrWHFwWlNBdDF1ZVVVcVp0RFF3YVdybnNMbkdrNTcxcFJNUmlobkU0YmpLRkYwemdhdF9abGs1YmdGZUhpUE1uSVlvNXlWZE5FTFlWbXZuSVp6RjVjOGF4QnJOVTE4ckRIRk8wYVJEUFkwMkQ4V3VMQVJnbmZxZjVVOU5jVHFDbWpvUU50ZjM1ZkQ3Nnl3ZGFETzE4SU5HSk1aWGZSS0prUEJKWlo5Q2pnVERfcDNraEhCdVRlVGJvVUFNMTZDMmkxWmhBUkZyMlVZMTdqS3pWT1d4bm1PTlhkWk5fRHEwUUp4dmtQeDhfTXFhb0F4Rkg1eDFmb3A3YzhFazY1REFiX25SZktQUWd4cWk4bGlrSl9HWnd6RXNUM3JCNzJiaENRUGFMQ05iRml5MVVpbFlkSUpoeXQ3QXA0eE5VNk9lY3ZjRFNVV0J2ZGFYUXU1cldGM1RvejdNd2JSVHdoc2o0R2NiMktZcDdWMVRlellJR05tdzBsbFJLV19aTkZfWFVudGt3bUI0UmxhaV9TTmZkUnNqOWxGUEhoTjhFcWtkZzRLR1h3ZlVhZG9KMWxqWmZiR1JPNVIwdmdIVS1lTTdjMDEzWTlidWNabWp4d0FwYzFITThrYTdJRXVSSjVwMlI4c0FDaHZyTlVKd0FKX2dpWHRWbm1fRXNYTmgyWnFTbXE4VzdKRnNNdGJVNUdSU0hNR3BGWmg1TlZYN2xWWmFWaHRTY0c4aXpQeGJ6cy1yZWNKNnF3bVdTVklLcXlFdWk3NklnWTBPUUhIRnFSWXktT1lBSDRYZEszS25RY3ctNDQtZlVCRXBqVVkxTWxwSDFFWXhkRmRaN1pNSC50cw\",D=\"false\"\n#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID=\"chunked\",NAME=\"1080p60 (source)\",AUTOSELECT=YES,DEFAULT=YES\n#EXT-X-STREAM-INF:BANDWIDTH=5238021,RESOLUTION=1920x1080,CODECS=\"avc1.64002A,mp4a.40.2\",VIDEO=\"chunked\",FRAME-RATE=60.000\nhttps://usw23.playlist.live-video.net/v1/playlist/CsgFY-UNv-kZsE5DctZOfabkimOsxcBk9fhYGde8MudWwRS8JA---8<---949\n#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID=\"720p60\",NAME=\"720p60\",AUTOSELECT=YES,DEFAULT=YES\n#EXT-X-STREAM-INF:BANDWIDTH=3422999,RESOLUTION=1280x720,CODECS=\"avc1.4D401F,mp4a.40.2\",VIDEO=\"720p60\",FRAME-RATE=60.000\nhttps://usw23.playlist.live-video.net/v1/playlist/CsYFWWYKjxzeCD7ohnhaQX0ro1FC_YzZbmfNQAJLjqkit4i4_A---8<---946\n#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID=\"720p30\",NAME=\"720p\",AUTOSELECT=YES,DEFAULT=YES\n#EXT-X-STREAM-INF:BANDWIDTH=2373000,RESOLUTION=1280x720,CODECS=\"avc1.4D401F,mp4a.40.2\",VIDEO=\"720p30\",FRAME-RATE=30.000\nhttps://usw23.playlist.live-video.net/v1/playlist/CsYFI4OA6ihgOCvpNnFfwPLDEpIsClN-qpZrC_IyFOPJ8sg4D----8<---946\n#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID=\"480p30\",NAME=\"480p\",AUTOSELECT=YES,DEFAULT=YES\n#EXT-X-STREAM-INF:BANDWIDTH=1427999,RESOLUTION=852x480,CODECS=\"avc1.4D401F,mp4a.40.2\",VIDEO=\"480p30\",FRAME-RATE=30.000\nhttps://usw23.playlist.live-video.net/v1/playlist/CsYFPKrE7CyYMW4BN7aLXc6XWmX2GbECgvHDQ0EcmHX-WvESMJ---8<---946\n#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID=\"360p30\",NAME=\"360p\",AUTOSELECT=YES,DEFAULT=YES\n#EXT-X-STREAM-INF:BANDWIDTH=630000,RESOLUTION=640x360,CODECS=\"avc1.4D401F,mp4a.40.2\",VIDEO=\"360p30\",FRAME-RATE=30.000\nhttps://usw23.playlist.live-video.net/v1/playlist/CsYFmGsU70BErVQmdKi5UkYI4ZdEc5cqWh3XZLYhzUM3uKDORD---8<---946\n#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID=\"160p30\",NAME=\"160p\",AUTOSELECT=YES,DEFAULT=YES\n#EXT-X-STREAM-INF:BANDWIDTH=230000,RESOLUTION=284x160,CODECS=\"avc1.4D401F,mp4a.40.2\",VIDEO=\"160p30\",FRAME-RATE=30.000\nhttps://usw23.playlist.live-video.net/v1/playlist/CsYF68BrnRvCCftbYvoWgnMVSIOUehjWs9XRfD9Z8NUcszTrRv---8<---946\n#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID=\"audio_only\",NAME=\"audio_only\",AUTOSELECT=NO,DEFAULT=NO\n#EXT-X-STREAM-INF:BANDWIDTH=160000,CODECS=\"mp4a.40.2\",VIDEO=\"audio_only\"\nhttps://usw23.playlist.live-video.net/v1/playlist/CsgFdF3yEakOxksZxoxnaTwLeDWsBDFZcu09CVHGK2up2sDlQJ---8<---949","СпискиСегментов":[],"Журнал":["  0.050 [Журнал] Журнал запущен 50мс","  0.050 [Настройки] Восстанавливаю настройки","  0.051 [Фокусник] Начальное состояние {\"лПоказан\":true,\"лАктивен\":false}","~ 0.051 [ПолноэкранныйРежим] Режим включен: false","  0.057 [Настройки] Настройки прочитаны из хранилища: {\"кОдновременныхЗагрузок\":3,\"лАвтоПоложениеЧата\":true,\"лАвтоперенаправлениеЗамечено\":true,\"лАвтоперенаправлениеРазрешено\":true,\"лМенятьГромкостьКолесом\":false,\"лПоказатьСтатистику\":true,\"лПредустановкаЗаполнена_буферизация\":true,\"лПредустановкаЗаполнена_оформление\":true,\"лПриглушить\":false,\"сНазваниеВарианта\":\"chunked\",\"сПредустановкаВыбрана_буферизация\":\"J0129\",\"сПредустановкаВыбрана_оформление\":\"J0123\",\"сПредыдущаяВерсия\":\"2022.2.7.1\",\"сЦветВыделения\":\"#ff8000\",\"сЦветГрадиента\":\"#ffff00\",\"сЦветЗаголовка\":\"#ffff00\",\"сЦветКнопок\":\"#402000\",\"сЦветФона\":\"#ff8000\",\"чВерсияНастроек\":2,\"чВертикальноеПоложениеЧата\":3,\"чГромкость2\":100,\"чДлительностьПовтора2\":-9007199254740991,\"чНачалоВоспроизведения\":1.5,\"чПоложениеПанелиЧата\":2,\"чПоследняяПроверкаОбновленияРасширения\":1712155028039,\"чРазмерБуфера\":1.5,\"чРастягиваниеБуфера\":9,\"чСлучайноеЧисло\":0.5341095705912817,\"чСостояниеЗакрытогоЧата\":0,\"чСостояниеЧата\":2}","  0.057 [Запускалка] Начало работы 57мс","~ 0.058 [Чат] Новое состояние панели: 2","  0.059 [Чат] Вставляю iframe https://www.twitch.tv/popout/solegenddairy/chat?no-mobile-redirect=true&popout=","  0.060 [Управление] Состояние трансляции изменилось с undefined на 1","  0.060 [События] Произошло событие управление-изменилосьсостояние","  0.060 [Пульс] Таймер запущен","  0.060 [Twitch] Отменяю обновление метаданных трансляции ТрансляцияЗавершена=true","  0.060 [i18n] Перевод документа","~ 0.061 [КартинкаВКартинке] Режим включен: false","~ 0.062 [Аудиоустройства] Получаю список медиаустройств","  0.062 [Список] Обновление списков 0 начнется через -Infinityмс","  0.093 [API] Хранилище печенек: 0","  0.094 [MediaElement] loadstart src=blob:chrome-extension://bhplkbgoehhhddaoolmakpocnenplmhf/23b059d9-d145-4cb9-8088-7b5392a1c2a0 currentSrc=blob:chrome-extension://bhplkbgoehhhddaoolmakpocnenplmhf/23b059d9-d145-4cb9-8088-7b5392a1c2a0 ••• [P] MSE.readyState=closed MSE.buffers=0 readyState=0 currentTime=0 buffered= duration=NaN seekable= played=","  0.103 [MediaSource] sourceopen ••• [P] MSE.buffers=0 readyState=0 currentTime=0 buffered= duration=NaN seekable= played=","  0.104 [Аудиоустройства] Текущее устройство ","  0.104 [Аудиоустройства] Медиаустройство kind=audioinput deviceId=default groupId=38ec6cb4be71214b749185c7448ec0fbde16bb71d7be9c9cd16b08b4f88b8ffc label=Default - Microphone Array (Realtek(R) Audio)","  0.104 [Аудиоустройства] Медиаустройство kind=audioinput deviceId=communications groupId=38ec6cb4be71214b749185c7448ec0fbde16bb71d7be9c9cd16b08b4f88b8ffc label=Communications - Microphone Array (Realtek(R) Audio)","  0.104 [Аудиоустройства] Медиаустройство kind=audioinput deviceId=0ec3036b0cb5da5045f20bc56fb81c11137135db1c479ef6260f23d82d18dc56 groupId=38ec6cb4be71214b749185c7448ec0fbde16bb71d7be9c9cd16b08b4f88b8ffc label=Microphone Array (Realtek(R) Audio)","  0.104 [Аудиоустройства] Медиаустройство kind=videoinput deviceId= groupId= label=","  0.104 [Аудиоустройства] Медиаустройство kind=audiooutput deviceId=default groupId=131ae487293b0065ff9dd0b0e8e8123e266288fc6f11b50d668c79a5af39fc08 label=Default - Digital TV (NVIDIA High Definition Audio)","  0.104 [Аудиоустройства] Медиаустройство kind=audiooutput deviceId=communications groupId=131ae487293b0065ff9dd0b0e8e8123e266288fc6f11b50d668c79a5af39fc08 label=Communications - Digital TV (NVIDIA High Definition Audio)","  0.104 [Аудиоустройства] Медиаустройство kind=audiooutput deviceId=c0d128365c4151d16b31bcaed7e40011b16e0d8a2f884e7aac2bb655e61147be groupId=38ec6cb4be71214b749185c7448ec0fbde16bb71d7be9c9cd16b08b4f88b8ffc label=Speakers (Realtek(R) Audio)","  0.104 [Аудиоустройства] Медиаустройство kind=audiooutput deviceId=44ff11aeae10ae2b6ca762f99ff0b2bf562d3bb199fe1d41b93e82364cc1acc9 groupId=131ae487293b0065ff9dd0b0e8e8123e266288fc6f11b50d668c79a5af39fc08 label=Digital TV (NVIDIA High Definition Audio)","  0.112 [API] Количество печенек: 17","  0.112 [События] Произошло событие twitch-полученыметаданныезрителя","  0.112 [Загрузчик] POST токен трансляции 0 не дольше 15000мс","  0.121 [Twitch] Обрабатываю заголовки запроса POST https://gql.twitch.tv","~ 0.154 [Twitch] Обрабатываю заголовки ответа https://www.twitch.tv/popout/solegenddairy/chat?no-mobile-redirect=true&popout=","~ 0.154 [Twitch] Удаляю заголовок X-Frame-Options","  0.166 [Twitch] Получен запрос на вставку сторонних расширений","  0.174 [Twitch] Посылаю ответ на вставку сторонних расширений: BTTV FFZ ","  0.496 [Загрузчик] Загрузил токен трансляции 0 за 385мс\n{\"data\":{\"streamPlaybackAccessToken\":{\"value\":\"{\\\"adblock\\\":false,\\\"authorization\\\":{\\\"forbidden\\\":false,\\\"reason\\\":\\\"\\\"},\\\"blackout_enabled\\\":false,\\\"channel\\\":\\\"solegenddairy\\\",\\\"channel_id\\\":491956882,\\\"chansub\\\":{\\\"restricted_bitrates\\\":[],\\\"view_until\\\":1924905600},\\\"ci_gb\\\":false,\\\"geoblock_reason\\\":\\\"\\\",\\\"device_id\\\":\\\"d1k8jBjR1zgXgQpBq1cM7J7NjEWGbS5L\\\",\\\"expires\\\":1712358394,\\\"extended_history_allowed\\\":false,\\\"game\\\":\\\"\\\",\\\"hide_ads\\\":false,\\\"https_required\\\":true,\\\"mature\\\":false,\\\"partner\\\":false,\\\"platform\\\":\\\"web\\\",\\\"player_type\\\":\\\"site\\\",\\\"private\\\":{\\\"allowed_to_view\\\":true},\\\"privileged\\\":false,\\\"role\\\":\\\"\\\",\\\"server_ads\\\":true,\\\"show_ads\\\":true,\\\"subscriber\\\":false,\\\"turbo\\\":false,\\\"user_id\\\":611531873,\\\"user_ip\\\":\\\"122.108.193.112\\\",\\\"version\\\":2}\",\"signature\":\"f404e7b670c9d9d1f601ed9405ff860f92741646\"}},\"extensions\":{\"durationMilliseconds\":79,\"requestID\":\"01HTR72ENYCBWQF0PR55EJJDVE\"}}","  0.496 [Загрузчик] GET список вариантов 0 не дольше 15000мс","  0.497 [Загрузчик] POST метаданные канала не дольше 15000мс","  0.498 [Twitch] Обрабатываю заголовки запроса GET https://usher.ttvnw.net","  0.502 [Twitch] Обрабатываю заголовки запроса POST https://gql.twitch.tv","  0.672 [Загрузчик] Загрузил список вариантов 0 за 176мс Размер=10386символов","@ 0.672 [Список] РассинхронизацияВремени=5008004мс ИдТрансляции=42551990718","  0.673 [Список] Количество вариантов в списке: 7","  0.673 [Список] Для списка 0 выбран вариант трансляции chunked/5238021. Сохраненный chunked/9007199254739991","  0.673 [Загрузчик] GET список сегментов 0 не дольше 6000мс","  0.673 [Отладка] Завершаю работу ••• [P] MSE.buffers=0 readyState=0 currentTime=0 buffered= duration=NaN seekable= played=","  0.673 [Очередь] ","~ 0.673 [Запускалка] Завершаю работу","~ 0.673 [Запускалка] Работа завершена"]}

i have no clue what most of it says.

**Comment by BURGERxBOY** [comment]
https://github.com/BURGERxBOY/alternate-player-for-twitch.tv-public-bug-issue-list/assets/135216471/d232931e-7a48-4781-a90e-bbc4f716cea6

can't send error reports to the dev either.

**Comment by BURGERxBOY** [comment]
it is getting worse, even after rebooting my pc, it did not fix it, and now it is on 2 of the alternate player tabs.
-- needs fixing URGENTLY.

**Comment by BURGERxBOY** [comment]
fixed.
